### ISSUE TITLE
Beta for 1.0 Error

### ISSUE THREAD

**Issue by DavidFW1960** [exxamalte/home-assistant-custom-components-nsw-rural-fire-service-fire-danger#8]
Version 1 beta has killed this with the following error:
```
2020-12-03 09:36:14 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Greater Sydney Region for nsw_rural_fire_service_fire_danger
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/nsw_rural_fire_service_fire_danger/__init__.py", line 77, in async_setup_entry
    manager = NswRfsFireDangerFeedEntityManager(hass, config_entry)
  File "/config/custom_components/nsw_rural_fire_service_fire_danger/__init__.py", line 112, in __init__
    self._rest = RestData(DEFAULT_METHOD, URL, None, None, None, DEFAULT_VERIFY_SSL)
TypeError: __init__() missing 1 required positional argument: 'verify_ssl'
```

**Comment by exxamalte** [comment]
Thanks, I can reproduce this issue.

This is related to a change of `RestData`'s signature in Home Assistant 0.118, and I will have to think about how to resolve this from this version onwards only.

**Comment by DavidFW1960** [comment]
Still getting an error
```
Logger: homeassistant.config_entries
Source: custom_components/nsw_rural_fire_service_fire_danger/__init__.py:122
First occurred: 8:29:05 AM (1 occurrences)
Last logged: 8:29:05 AM

Error setting up entry Greater Sydney Region for nsw_rural_fire_service_fire_danger
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/nsw_rural_fire_service_fire_danger/__init__.py", line 82, in async_setup_entry
    manager = NswRfsFireDangerFeedEntityManager(hass, config_entry)
  File "/config/custom_components/nsw_rural_fire_service_fire_danger/__init__.py", line 122, in __init__
    self._rest = RestData(
TypeError: __init__() missing 1 required positional argument: 'verify_ssl'
```

**Comment by exxamalte** [comment]
Could you please send the exact Home Assistant version you are getting this error with?

I tested the current version on 0.118.4 and 0.119.0dev.

**Comment by DavidFW1960** [comment]
It's the official beta 1.0.0b0

**Comment by exxamalte** [comment]
Thanks, I will need to fix my version check then.
